name: Sync products from Content Island

on:
  repository_dispatch:
    types: [sync-products]

jobs:
  sync-products:
    runs-on: ubuntu-latest
    steps:
      - name: Sync products
        run: |
          curl -X POST -H "Authorization: Bearer ${{secrets.CONTENT_ISLAND_ACCESS_TOKEN}}" ${{secrets.SYNC_PRODUCTS_URL}}
