name: Sync products from Content Island

on:
  repository_dispatch:
    types: [sync-products]

jobs:
  sync-products:
    runs-on: ubuntu-latest
    steps:
      - name: Sync products
        run: curl -X POST ${{secrets.SYNC_PRODUCTS_URL}} --http1.1
